/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_geniusgithub_mediarender_jni_PlatinumJniProxy */

#ifndef _Included_com_geniusgithub_mediarender_jni_PlatinumJniProxy
#define _Included_com_geniusgithub_mediarender_jni_PlatinumJniProxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_geniusgithub_mediarender_jni_PlatinumJniProxy
 * Method:    startMediaRender
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_com_bftv_service_dlna_jni_PlatinumJniProxy_startMediaRender
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_geniusgithub_mediarender_jni_PlatinumJniProxy
 * Method:    stopMediaRender
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_bftv_service_dlna_jni_PlatinumJniProxy_stopMediaRender
  (JNIEnv *, jclass);

/*
 * Class:     com_geniusgithub_mediarender_jni_PlatinumJniProxy
 * Method:    responseGenaEvent
 * Signature: (I[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_bftv_service_dlna_jni_PlatinumJniProxy_responseGenaEvent
  (JNIEnv *, jclass, jint, jbyteArray, jbyteArray);

/*
 * Class:     com_geniusgithub_mediarender_jni_PlatinumJniProxy
 * Method:    enableLogPrint
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_bftv_service_dlna_jni_PlatinumJniProxy_enableLogPrint
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
